node_expire.settings:
  type: mapping
  label: Settings
  mapping:
    node_expire_handle_content_expiry:
      type: integer
    node_expire_date_entry_elements:
      type: integer
    node_expire_past_date_allowed:
      type: integer
